### ISSUE TITLE
bug: clicking on a message twice, (not double clicking) enables toolbar button

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/list-unsubscribe-zimlet#1]
bug: clicking on a message twice, (not double clicking) enables toolbar button
to unsubscribe from the mailing list, even if no unsubscribe header is present.

So one can unsubscribe from random mail -> fail

**Comment by meersjo** [comment]
I just installed it, and still see this behaviour :-(

I'm on Zimbra 8.6.0; anything else I can provide to help ?

**Comment by meersjo** [comment]
Nothing relevant seems to get logged; also happens in per-message view (as per another old bug).

**Comment by barrydegraaff** [comment]
Hello Meersjo,

I tried it here, and it just works, on 8.6 the latest patch.

Did you install the zip or did you use development mode?
https://github.com/Zimbra-Community/list-unsubscribe-zimlet#installing-in-development-mode

**Comment by meersjo** [comment]
I installed the zip from master, as indicated in the readme. Tested on Firefox and Seamonkey, which - durr - is really the same browser.

I've now done a quick test in Chrome, and the bug is still there - but I now also noticed that it's apparently dependent on the particular mail. The one where it occurs only has a List-Unsubscribe header, whereas the one where it works has both that and a List-Unsubscribe-Post header.

Can I get you the two mails somewhere ? Don't want to attach them here :-p

**Comment by barrydegraaff** [comment]
Hi,

Please drag the 2 mail messages to a new folder in Zimbra
and export that to tgz via the preferences.

Then you can attach em to info@barrydegraaff.tk

**Comment by barrydegraaff** [comment]
It turns out those emails do not work as they do not follow the RFC
https://www.ietf.org/rfc/rfc2369.txt

The header is not valid:
List-Unsubscribe: http://cdn.flx.....8595035576c

It should be:
List-Unsubscribe: <http://cdn.flx.....595035576c>

There is also a new standard coming, but I do not implement that one yet:
https://tools.ietf.org/html/rfc8058

So I guess the sender needs to fix their stuff.

**Comment by meersjo** [comment]
Then there is, technically, still a bug: the header is invalid, yet the button is shown :-)

Personally, I tend to favour some leeway in implementation of standards, but it's your code, so your decision. I might fork it, though :-p

**Comment by barrydegraaff** [comment]
Its easy, just make the regular expression also match the url without <>
then it would just work.

If you can, fork, fix and send a pull request, I am happy to merge it!

Barry

**Comment by barrydegraaff** [comment]
@meersjo can you undeploy the zimlet, and deploy in development mode.
I fixed it so that the incorrect header should result in the button being removed.

Thanks!
