### ISSUE TITLE
Last Unsubscribed in Compose Tab at Login

### ISSUE THREAD

**Issue by sonoracomm** [Zimbra-Community/list-unsubscribe-zimlet#6]
Hi,

Thank you for this useful add-on.  We use it with Zimbra OSE 8.8.11 (patched), Zextras and a couple of other addons.

After using the unsubscribe button...

At ZWC login, a Compose tab is opened with the last-used unsubscribe address in the To: field, almost like it was a Draft opened for edit.  See attached.

Deleting the 'draft' (closing the tab; cancelling the edit) does not keep it from appearing at the next ZWC login.

Any ideas?

Thanks much,

G
![zimbra_compose_after_unsubscribe](https://user-images.githubusercontent.com/20728868/54288974-96787180-4565-11e9-8778-178b50b8afff.png)

**Comment by ghost** [comment]
yes, that is because the unsubscribe zimlet uses the URL to do it's things.

Just removing the ?view=... part from the url will do the trick

**Comment by sonoracomm** [comment]
I'm an idiot.

Thank you.

> yes, that is because the unsubscribe zimlet uses the URL to do it's things.
> Just removing the ?view=... part from the url will do the trick

G
